# Generated by Django 5.0.1 on 2026-04-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(help_text='Code submitted by student')),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('compilation_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('timeout', 'Timeout')], default='pending', max_length=30)),
                ('test_cases_passed', models.IntegerField(default=0)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('execution_output', models.TextField(blank=True, help_text='Output from code execution')),
                ('error_message', models.TextField(blank=True, help_text='Error message if any')),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('memory_used_mb', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coding_submissions',
            },
        ),
        migrations.CreateModel(
            name='CodingTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_order', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('actual_output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('memory_used_mb', models.FloatField(blank=True, null=True)),
                ('coding_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='submissions.codingsubmission')),
            ],
            options={
                'db_table': 'coding_test_case_results',
                'ordering': ['test_case_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_attempted', 'Not Attempted'), ('attempted', 'Attempted'), ('submitted', 'Submitted')], default='not_attempted', max_length=20)),
                ('marks_obtained', models.FloatField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.examenrollment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questions.question')),
            ],
            options={
                'db_table': 'question_submissions',
            },
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='questions.mcqoption')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submission', to='submissions.questionsubmission')),
            ],
            options={
                'db_table': 'mcq_submissions',
            },
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submission', to='submissions.questionsubmission'),
        ),
        migrations.AddIndex(
            model_name='questionsubmission',
            index=models.Index(fields=['enrollment', 'question'], name='question_su_enrollm_a738f2_idx'),
        ),
        migrations.AddIndex(
            model_name='questionsubmission',
            index=models.Index(fields=['status'], name='question_su_status_a263bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsubmission',
            unique_together={('enrollment', 'question')},
        ),
    ]
