# Generated by Django 5.0.1 on 2026-04-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mcq_questions',
            },
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('mcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.mcqquestion')),
            ],
            options={
                'db_table': 'mcq_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('coding', 'Coding Question')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('marks', models.FloatField(default=1)),
                ('negative_marks', models.FloatField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq', to='questions.question'),
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('csharp', 'C#'), ('go', 'Go')], max_length=50)),
                ('starter_code', models.TextField(help_text='Initial code provided to student')),
                ('solution_code', models.TextField(help_text='Reference solution')),
                ('time_limit_seconds', models.IntegerField(default=30, help_text='Time limit for code execution')),
                ('memory_limit_mb', models.IntegerField(default=256, help_text='Memory limit in MB')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding', to='questions.question')),
            ],
            options={
                'db_table': 'coding_questions',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for the test case')),
                ('expected_output', models.TextField(help_text='Expected output')),
                ('is_visible', models.BooleanField(default=True, help_text='Visible to student during exam')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.codingquestion')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'question_type'], name='questions_exam_id_92d1f6_idx'),
        ),
    ]
