# Generated by Django 5.0.1 on 2026-04-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Total exam duration in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('total_marks', models.FloatField(default=100)),
                ('passing_marks', models.FloatField(default=40)),
                ('negative_marking', models.FloatField(default=0)),
                ('enable_camera', models.BooleanField(default=True)),
                ('enable_mic', models.BooleanField(default=True)),
                ('enable_screenshot', models.BooleanField(default=True)),
                ('record_screen', models.BooleanField(default=True)),
                ('record_video', models.BooleanField(default=True)),
                ('fullscreen_required', models.BooleanField(default=True)),
                ('tab_switch_allowed', models.BooleanField(default=False)),
                ('violation_threshold', models.IntegerField(default=3)),
                ('score_reduction_per_violation', models.FloatField(default=10)),
                ('allow_multiple_attempts', models.BooleanField(default=False)),
                ('show_answers_after_exam', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('started', 'Started'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('total_violations', models.IntegerField(default=0)),
                ('final_violations', models.IntegerField(default=0)),
                ('score_reduction', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'exam_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
