# Generated by Django 5.0.1 on 2026-04-02 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['instructor'], name='exams_instruc_0ff10d_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_status_863d01_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time'], name='exams_start_t_bab18d_idx'),
        ),
        migrations.AddIndex(
            model_name='examenrollment',
            index=models.Index(fields=['exam', 'student'], name='exam_enroll_exam_id_4b9013_idx'),
        ),
        migrations.AddIndex(
            model_name='examenrollment',
            index=models.Index(fields=['status'], name='exam_enroll_status_d03757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examenrollment',
            unique_together={('exam', 'student')},
        ),
    ]
