# Generated by Django 5.0.1 on 2026-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
