# Generated by Django 5.0.1 on 2026-04-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_course_exam_course_courseenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, help_text='Total time taken by student in seconds'),
        ),
    ]
