# Generated by Django 5.0.1 on 2026-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examenrollment_time_taken_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='is_auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
