# Generated by Django 5.0.1 on 2026-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examenrollment_is_auto_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='integrity_score',
            field=models.FloatField(default=100.0, help_text='Calculated integrity score based on violations'),
        ),
    ]
