# Generated by Django 6.0.5 on 2026-05-26 07:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examenrollment_integrity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('starter_code', models.TextField()),
                ('solution_code', models.TextField()),
                ('programming_language', models.CharField(default='python', max_length=50)),
                ('test_cases_json', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'coding_challenges',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='advanced_options_json',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='course',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='daily_learning_time_minutes',
            field=models.IntegerField(blank=True, default=120, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_goal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('is_passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.codingchallenge')),
            ],
            options={
                'db_table': 'challenge_submissions',
            },
        ),
        migrations.CreateModel(
            name='CourseGenerationTask',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('youtube_url', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(default='Initializing...', max_length=100)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('request_payload_json', models.TextField(blank=True, default='{}')),
                ('daily_learning_time_minutes', models.IntegerField(blank=True, default=120, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, default='')),
                ('advanced_options_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_generation_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_generation_tasks',
            },
        ),
        migrations.CreateModel(
            name='CourseGenerationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('cached_output', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exams.coursegenerationtask')),
            ],
            options={
                'db_table': 'course_generation_steps',
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='exams.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_details', to='exams.courseenrollment')),
            ],
            options={
                'db_table': 'course_progress',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(blank=True, default=60, null=True)),
                ('learning_day', models.IntegerField(blank=True, default=1, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.CharField(blank=True, max_length=20, null=True)),
                ('watch_start_seconds', models.IntegerField(blank=True, default=0, null=True)),
                ('watch_end_seconds', models.IntegerField(blank=True, default=0, null=True)),
                ('source_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='exams.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FinalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_final_exams', to='exams.exam')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='exams.module')),
            ],
            options={
                'db_table': 'final_exams',
            },
        ),
        migrations.AddField(
            model_name='codingchallenge',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_challenges', to='exams.module'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='exams.module')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='exams.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(default='general', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('log_details', models.TextField(blank=True, null=True)),
                ('final_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to='exams.finalexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_logs',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('passing_score', models.IntegerField(default=70)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exams.module')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.FloatField()),
                ('is_passed', models.BooleanField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options_json', models.TextField(help_text='JSON serialized array of choice items')),
                ('correct_option_index', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.quiz')),
            ],
            options={
                'db_table': 'quiz_questions',
            },
        ),
        migrations.CreateModel(
            name='RevisionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_sessions', to='exams.module')),
            ],
            options={
                'db_table': 'revision_sessions',
            },
        ),
        migrations.CreateModel(
            name='VideoTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='exams.module')),
            ],
            options={
                'db_table': 'video_timestamps',
                'ordering': ['timestamp_seconds'],
            },
        ),
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(max_length=255, unique=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_transcript', models.TextField()),
                ('processed_chunks_json', models.TextField(blank=True, null=True)),
                ('cached_topics_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='exams.course')),
            ],
            options={
                'db_table': 'video_transcripts',
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time_seconds', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress_records', to='exams.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_progress',
                'unique_together': {('student', 'module')},
            },
        ),
    ]
