# Generated by Django 6.0.5 on 2026-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_codingchallenge_course_advanced_options_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='youtube_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videotranscript',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
