# Generated by Django 5.0.1 on 2026-09-04 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_videotranscript_youtube_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Algebra', max_length=100)),
                ('symptom', models.CharField(default='Struggles with word problems despite passing test', max_length=255)),
                ('raw_question', models.TextField(help_text='Student original query/question')),
                ('status', models.CharField(choices=[('analyzing', 'Analyzing'), ('diagnosed', 'Diagnosed'), ('pending_approval', 'Pending Teacher Approval'), ('approved', 'Approved by Teacher'), ('adopted', 'Adopted by Student')], default='analyzing', max_length=30)),
                ('overall_mastery_score', models.FloatField(default=0.0)),
                ('gap_summary', models.TextField(blank=True, default='')),
                ('recommended_path_title', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_agent_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('student_interaction', 'Student Interaction Agent'), ('mastery_assessment', 'Mastery Assessment Agent'), ('gap_diagnosis', 'Gap Diagnosis Agent'), ('path_sequencing', 'Path Sequencing Agent'), ('teacher_notification', 'Teacher Notification Agent')], max_length=40)),
                ('step_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('payload_json', models.TextField(default='{}', help_text='Structured JSON payload containing agent-specific artifacts')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='exams.learningagentsession')),
            ],
            options={
                'db_table': 'agent_interaction_logs',
                'ordering': ['step_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Informational'), ('moderate', 'Moderate Gap Detected'), ('high', 'High Concept-Score Disparity')], default='high', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('modified', 'Modified by Teacher'), ('mentorship_scheduled', '1-on-1 Mentorship Scheduled'), ('dismissed', 'Dismissed')], default='pending', max_length=30)),
                ('dossier_summary', models.TextField(help_text='Detailed diagnosis compiled by Teacher Notification Agent')),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_interventions', to='exams.learningagentsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interventions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_interventions',
                'ordering': ['-created_at'],
            },
        ),
    ]
