# Generated by Django 5.0.1 on 2026-09-04 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_learningagentsession_agentinteractionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRemediationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(default='Python for Beginners', max_length=255)),
                ('module_title', models.CharField(default='Variables & Control Flow', max_length=255)),
                ('concept_name', models.CharField(help_text='e.g. Loop Iteration & Range Off-By-One Logic', max_length=255)),
                ('status', models.CharField(choices=[('needs_practice', 'Needs Practice'), ('in_progress', 'In Progress'), ('mastered', 'Mastered / Ready for Re-exam')], default='needs_practice', max_length=30)),
                ('quiz_score', models.IntegerField(default=85)),
                ('challenge_score', models.IntegerField(default=30)),
                ('diagnosis_reason', models.TextField(help_text='Explains why coding challenge failed despite good quiz score')),
                ('starter_code', models.TextField(blank=True, default='')),
                ('solution_code', models.TextField(blank=True, default='')),
                ('practice_hint', models.TextField(blank=True, default='')),
                ('test_cases_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_remediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'code_remediation_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
