# Generated by Django 5.0.1 on 2026-04-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('ended', 'Ended')], default='active', max_length=20)),
                ('screen_recording_path', models.FileField(blank=True, null=True, upload_to='recordings/screen/')),
                ('video_recording_path', models.FileField(blank=True, null=True, upload_to='recordings/video/')),
                ('audio_recording_path', models.FileField(blank=True, null=True, upload_to='recordings/audio/')),
                ('camera_enabled', models.BooleanField(default=True)),
                ('mic_enabled', models.BooleanField(default=True)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('total_session_duration_seconds', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('total_screenshots', models.IntegerField(default=0)),
                ('fps_average', models.FloatField(default=0, help_text='Average Frames Per Second')),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exams.examenrollment')),
            ],
            options={
                'db_table': 'exam_sessions',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('question_viewed', 'Question Viewed'), ('answer_submitted', 'Answer Submitted'), ('code_executed', 'Code Executed'), ('camera_status_changed', 'Camera Status Changed'), ('mic_status_changed', 'Microphone Status Changed'), ('fullscreen_changed', 'Fullscreen Status Changed'), ('window_switched', 'Window Switched'), ('copy_paste', 'Copy-Paste Activity'), ('keyboard_activity', 'Keyboard Activity'), ('mouse_activity', 'Mouse Activity')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proctoring.examsession')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('phone_detected', 'Phone/Mobile Device Detected'), ('gadget_detected', 'Electric Gadget Detected'), ('tab_switch', 'Tab/Window Switched'), ('fullscreen_exit', 'Exited Fullscreen'), ('camera_off', 'Camera Turned Off'), ('mic_off', 'Microphone Turned Off'), ('suspicious_activity', 'Suspicious Activity Detected'), ('unusual_behavior', 'Unusual Behavior'), ('multiple_face', 'Multiple Faces Detected'), ('no_face', 'Face Not Detected')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('evidence_screenshot', models.ImageField(blank=True, null=True, upload_to='violations/screenshots/')),
                ('evidence_video_frame', models.FileField(blank=True, null=True, upload_to='violations/frames/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='exams.examenrollment')),
            ],
            options={
                'db_table': 'proctoring_violations',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('violation', 'Violation Detected'), ('random', 'Random Check'), ('flagged', 'Flagged Activity')], default='random', max_length=100)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_captures', to='proctoring.examsession')),
            ],
            options={
                'db_table': 'screen_captures',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['enrollment'], name='exam_sessio_enrollm_453b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status'], name='exam_sessio_status_954ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['session', 'activity_type'], name='activity_lo_session_2e22fd_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['timestamp'], name='activity_lo_timesta_ef2c57_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['enrollment'], name='proctoring__enrollm_92d209_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['violation_type'], name='proctoring__violati_a7cc32_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringviolation',
            index=models.Index(fields=['severity'], name='proctoring__severit_b84c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='screencapture',
            index=models.Index(fields=['session'], name='screen_capt_session_b2e5a7_idx'),
        ),
        migrations.AddIndex(
            model_name='screencapture',
            index=models.Index(fields=['reason'], name='screen_capt_reason_349f50_idx'),
        ),
    ]
