# Generated by Django 5.0.1 on 2026-04-03 07:19

import exam_proctor_backend.apps.proctoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringviolation',
            name='detections',
            field=models.JSONField(blank=True, default=dict, help_text='AI Detections at the time of violation'),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='evidence_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=exam_proctor_backend.apps.proctoring.models.violation_screenshot_path),
        ),
    ]
