# Generated by Django 6.0.5 on 2026-05-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctoringviolation_detections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('question_viewed', 'Question Viewed'), ('answer_submitted', 'Answer Submitted'), ('code_executed', 'Code Executed'), ('camera_status_changed', 'Camera Status Changed'), ('mic_status_changed', 'Microphone Status Changed'), ('fullscreen_changed', 'Fullscreen Status Changed'), ('window_switched', 'Window Switched'), ('copy_paste', 'Copy-Paste Activity'), ('keyboard_activity', 'Keyboard Activity'), ('mouse_activity', 'Mouse Activity'), ('violation_detected', 'Violation Detected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('phone_detected', 'Phone/Mobile Device Detected'), ('mobile_phone', 'Mobile Phone Identified'), ('gadget_detected', 'Electric Gadget Detected'), ('tab_switch', 'Tab/Window Switched'), ('tab_switching', 'Tab Switching Activity'), ('fullscreen_exit', 'Exited Fullscreen'), ('camera_off', 'Camera Turned Off'), ('mic_off', 'Microphone Turned Off'), ('suspicious_activity', 'Suspicious Activity Detected'), ('unusual_behavior', 'Unusual Behavior'), ('multiple_people', 'Multiple People Detected'), ('multiple_face', 'Multiple Faces Detected'), ('absence', 'Candidate Absence'), ('no_face', 'Face Not Detected'), ('forbidden_item', 'Forbidden Item Detected'), ('partial_face', 'Partial Face Visibility'), ('gaze_aversion', 'Gaze Aversion (Looking Away)')], max_length=50),
        ),
    ]
